### ISSUE TITLE
skewer-css-eval-buffer won't delete rules already applied

### ISSUE THREAD

**Issue by L42y** [skeeto/skewer-mode#17]
For example, if I wrote these rules:

``` css
header {
    height: 44px;
    background: red;
}
```

but then I changed the rules:

``` css
header {
    height: 44px;
}
```

the red background is still here, is there a way to get rid of this problem?
